config/routes.rb
Rails.application.routes.draw do

  get 'users/new'

  resources :players
  resources :countries
  resources :teams
  resources :stadia
  
  post '/signup',  to: 'users#new'
  post '/signin',  to: 'sessions#new'
  get '/signout', to: 'sessions#destroy', via: :delete
  
  root to: 'static_pages#home'
  
  get '/help',    to: 'static_pages#help'
  get '/about',   to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

end

app/controllers/stadia_controller.rb
class StadiaController < ApplicationController
  before_action :set_stadium, only: [:show, :edit, :update, :destroy]

  # GET /stadia
  # GET /stadia.json
  def index
    @stadia = Stadium.all
  end

  # GET /stadia/1
  # GET /stadia/1.json
  def show
  end

  # GET /stadia/new
  def new
    @stadium = Stadium.new
  end

  # GET /stadia/1/edit
  def edit
  end

  # POST /stadia
  # POST /stadia.json
  def create
    @stadium = Stadium.new(stadium_params)

    respond_to do |format|
      if @stadium.save
        format.html { redirect_to @stadium, notice: 'Stadium was successfully created.' }
        format.json { render :show, status: :created, location: @stadium }
      else
        format.html { render :new }
        format.json { render json: @stadium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stadia/1
  # PATCH/PUT /stadia/1.json
  def update
    respond_to do |format|
      if @stadium.update(stadium_params)
        format.html { redirect_to @stadium, notice: 'Stadium was successfully updated.' }
        format.json { render :show, status: :ok, location: @stadium }
      else
        format.html { render :edit }
        format.json { render json: @stadium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stadia/1
  # DELETE /stadia/1.json
  def destroy
    @stadium.destroy
    respond_to do |format|
      format.html { redirect_to stadia_url, notice: 'Stadium was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stadium
      @stadium = Stadium.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stadium_params
      params.require(:stadium).permit(:name, :city, :owner_club, :capacity, :image_url, :description, :status)
    end
end

app/helpers/stadia_helper.rb
module StadiaHelper
end

app/views/stadia/_form.html.erb
<%= form_for(@stadium) do |f| %>
  <% if @stadium.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stadium.errors.count, "error") %> prohibited this stadium from being saved:</h2>

      <ul>
      <% @stadium.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :owner_club %><br>
    <%= f.text_field :owner_club %>
  </div>
  <div class="field">
    <%= f.label :capacity %><br>
    <%= f.number_field :capacity %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.check_box :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stadia/edit.html.erb
<h1>Editing stadium</h1>

<%= render 'form' %>

<%= link_to 'Show', @stadium %> |
<%= link_to 'Back', stadia_path %>

app/views/stadia/index.html.erb
<h1>Listing stadia</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>City</th>
      <th>Owner club</th>
      <th>Capacity</th>
      <th>Image url</th>
      <th>Description</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stadia.each do |stadium| %>
      <tr>
        <td><%= stadium.name %></td>
        <td><%= stadium.city %></td>
        <td><%= stadium.owner_club %></td>
        <td><%= stadium.capacity %></td>
        <td><%= stadium.image_url %></td>
        <td><%= stadium.description %></td>
        <td><%= stadium.status %></td>
        <td><%= link_to 'Show', stadium %></td>
        <td><%= link_to 'Edit', edit_stadium_path(stadium) %></td>
        <td><%= link_to 'Destroy', stadium, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stadium', new_stadium_path %>

app/views/stadia/new.html.erb
<h1>New stadium</h1>

<%= render 'form' %>

<%= link_to 'Back', stadia_path %>

app/views/stadia/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @stadium.name %>
</p>

<p>
  <strong>City:</strong>
  <%= @stadium.city %>
</p>

<p>
  <strong>Owner club:</strong>
  <%= @stadium.owner_club %>
</p>

<p>
  <strong>Capacity:</strong>
  <%= @stadium.capacity %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @stadium.image_url %>
</p>

<p>
  <strong>Description:</strong>
  <%= @stadium.description %>
</p>

<p>
  <strong>Status:</strong>
  <%= @stadium.status %>
</p>

<%= link_to 'Edit', edit_stadium_path(@stadium) %> |
<%= link_to 'Back', stadia_path %>